### ISSUE TITLE
KB vs KiB etc on Binary/Bytes.html

### ISSUE THREAD

**Issue by masonjamie** [ascholerChemeketa/cs160Reader#1]
KB/MB/GB etc have been redefined from binary base 2^10/2^20/2^30 etc to the decimal base 10^3/10^6/10^9 etc to avoid conflict with the SI metric system.  The binary versions are now represented by Kilibytes (KiB), Megibytes (MiB), and Gigibytes (GiB) etc.  Recommend illustrating both on the conversion table.

**Comment by ascholerChemeketa** [comment]
Done!
